= tlsrpt-reportd(1)
Boris Lohner
v0.6.0
:production-warning: This option must not be used on production systems!
:doctype: manpage
:manmanual: tlsrpt-reportd
:mansource: tlsrpt-reportd
:man-linkstyle: pass:[blue R < >]
:varpar-configsection: tlsrpt_reportd
:varpar-daemonname: tlsrpt-reportd
:varpar-environmentprefix: TLSRPT_REPORTD_

== Name

tlsrpt-reportd - A daemon to create and deliver TLSRPT reports according to RFC 8460.

== Synopsis

*tlsrpt-reportd* [_OPTION_]

== Description
The tlsrpt-reportd is the final component in the TLSRPT framework.
A MTA (Mail Transfer Agent) reports successful delivery or encountered errors via libtlsrpt to a tlsrpt-collectd which collects and pre-aggregates the data.
The tlsrpt-fetcher associated with a tlsrpt-collectd transfers the pre-aggregated data to the tlsrpt-reportd.
The tlsrpt-reportd can retrieve data from multiple tlsrpt-fetchers and aggregates the pre-aggregated data into the final reports.
Those reports are gzip-compressed and sent out to the destinations as specified in the TLSRPT DNS records of the domains that have received emails from the MTA.

A simple data flow diagram visualizing the interaction of the components looks like this:
  (MTA)
    v
  libtlsrt
    v
  tlsrpt-collectd
    v
  (storage)
    v
  tlsrpt-fetcher
    v
  tlsrpt-reportd
    v
  (report destination)

== Options

=== Report creation and configuration options

*--contact_info*=_addr_::
Use _addr_ as contact info in the TLSRPT report according to RFC 8460.

*--organization_name*=_descr_::
Use _descr_ as name of the organization sending the TLSRPT report according to RFC 8460. 

*--sender_address*=_email_::
Use _email_ as "From:" address when sending reports via email.

*--fetchers*=_list_::
List of fetcher commands to retrieve data.
Multiple fetcher commands can be given separated by commas.

*--dbname*=_path_::
Use SQLite data base at location _path_.

*--compression_level*=_n_::
Use compression level _n_ to gzip-compress the TLSRPT reports.

*--keep_days*=_n_::
Keep old data for _n_ days before deleting from the database. 

=== Report delivery options

*--spread_out_delivery*=_sec_::
Spread out the delivery of TLSRPT reports over _sec_ seconds.
The minimum value is 1 and causes all reports to be sent out immediately.
This setting should be set to several hours according to RFC8460, section 4.1.
For example, set spread_out_delivery to 14400 to spread out the delivery of the reports over four hours.

*--sendmail_script*=_path_::
Use the script _path_ to send a TLSRPT report via email.

*--sendmail_timeout*=_sec_::
Set timeout of _sec_ seconds for email requests to deliver reports.

 
*--http_script*=_path_::
Use the script _path_ to upload a TLSRPT report via HTTP(S).

*--http_timeout*=_sec_::
Set timeout of _sec_ seconds for HTTP POST requests to deliver reports.

*--max_retries_delivery*=_n_::
Give up after _n_ failed attempts to deliver a report to its destination.


*--min_wait_delivery*=_sec_::
Minimum time to wait before retrying a failed report delivery attempt.

*--max_wait_delivery*=_sec_::
Maximum time to wait before retrying a failed report delivery attempt.


*--http_upload_map*=_path_::
Load a transformation map for HTTPS report destinations from file _path_. 
Cannot be used in combination with *--debug_send_http_dest*!

*--mail_destination_map*=_path_::
Load a transformation map for SMTP report destinations from file _path_.
Cannot be used in combination with *--debug_send_mail_dest*!

*--tlsrpt_record_map*=_path_::
Load a transformation map for all report destinations based on the TLSRPT domain from file _path_.
Cannot be used in combination with *--debug_send_file_dest*!

=== Options controlling the interaction with one or more tlsrpt-collectd

*--max_collectd_timediff*=_sec_::
Log a warning if the collectd clock reported by its fetcher differs by more than _sec_ seconds from the reportd´s clock.
The reportd starts querying the fetchers _sec_ seconds after the UTC day change, so a clock difference bigger than _sec_ seconds indicates the collectd might not yet been ready to provide the complete data for the previous day.

*--max_collectd_timeout*=_sec_::
Wait at most _sec_ seconds for a fetcher to finish a request for data from its collectd.


*--max_retries_domaindetails*=_n_::
Give up after _n_ failed attempts to retrieve report details for a domain.

*--min_wait_domaindetails*=_sec_::
Minimum time to wait before retry after a failed attempt to get the report details for a domain from a tlsrpt-collectd.

*--max_wait_domaindetails*=_sec_::
Maximum time to wait before retry after a failed attempt to get the report details for a domain from a tlsrpt-collectd.


*--max_retries_domainlist*=_n_:: 
Give up after _n_ failed attempts to retrieve the list of domains from a tlsrpt-collectd. 

*--min_wait_domainlist*=_sec_::
Minimum time to wait before retry after a failed attempt to get the list of domains from a tlsrpt-collectd.

*--max_wait_domainlist*=_sec_::
Maximum time to wait before retry after a failed attempt to get the list of domains from a tlsrpt-collectd.


*--interval_main_loop*=_sec_::
Wake up an idle main loop even if there are no tasks after _sec_ seconds of inactivity.


=== Debug and development options

*--debug_db*=_n_::
Control database debugging: 0 turns database debugging off, 1 activates logging of database statements.

*--debug_send_file_dest*=_dir_::
Save reports into directory _dir_ in addition to their delivery via email or HTTP POST requests.
Cannot be used in combination with *--tlsrpt_record_map*!

*--debug_send_mail_dest*=_path_::
Override the email destination to send out reports via email.
Please note: With this option set, reports to email destinations will not be sent ot the requested destination from the TLSRPT DNS record but to this replacement address instead!
{production-warning}
Cannot be used in combination with *--mail_destination_map*!


*--debug_send_http_dest*=_path_::
Override the HTTP POST destination to send out reports via HTTP POST requests.
Please note: With this option set, reports to HTTP POST destinations will not be sent ot the requested destination from the TLSRPT DNS record but to this replacement URL instead!
{production-warning}  
Cannot be used in combination with *--http_upload_map*!


include::manpage-common-options.adoc[]

== Destination Mapping

The *--tlsrpt_record_map*, *--http_upload_map* and *--mail_destination_map* options allow a mapping of the report destinations retrieved from the TLSRPT record based on the domain the report is created for.

All maps are processed on a "first match wins" manner. No further rules are processed after a rule has matched. 

The *--tlsrpt_record_map* is used first to transform the whole set of destinations.
The *--http_upload_map* and *--mail_destination_map* options allow for further modifications to report destinations matching the "mailto:" or "https:" URI scheme and they inspect the report destination to determine if the rule applies, not the domain for which the report is created.

Each map line has the format:
*match* *action* [*parameters*]

*match* is of the form "matchtype:pattern".
Supported match tyoes are: "domain:" and "regexp:".

The "domain:" prefix can be omitted, i.e. without a match tyoe specified the "domain:" match style is the default.
A "domain:" match matches the domain part of a "mailto:" URI in the *--mail_destination_map* and the domain part of an "https:" URI in the *--http_upload_map*.
A "domain:" match can match a complete domain name or if it starts with a "." it matches all subdomains. A single "." matches every domain name. A trailing "." after a domain name is ignored.

The domain name "many.sub.domains.example.com" would not be matched by "sub.domains.example.com" or "sub.domains.example.com." without a leading dot, but it would be matched by these domain match expressions:

 - many.sub.domains.example.com.
 - many.sub.domains.example.com
 - .sub.domains.example.com.
 - .sub.domains.example.com
 - .domains.example.com.
 - .domains.example.com
 - .example.com.
 - .example.com
 - .com.
 - .com
 - .

A "regexp:" style match in the *--tlsrpt_record_map* matches against the domain name the report is created for.
A "regexp:" style match in the *--http_upload_map* and *--mail_destination_map* maps matches against the whole report destination, not just the extracted domain part.

The *action* can be on of "ACCEPT", "DISCARD", "APPEND", "REPLACE" and "REGEXP".
"ACCEPT" actions just accept the report destinations as they are. 
"DISCARD" actions return an empty set of report destinations, no report will be sent out.
"APPEND" actions supply additional report destinations.
"REPLACE" actions replace the report destinations with other destinations.
"REGEXP" actions transform each matching report destination according to their two parameters: a matching regexp and a substitution.

"APPEND" and "REPLACE" and "REGEXP" actions can introduce other URI schemes.
tlsrpt-reportd understands in addition to the "mailto:" and "https:" URI schemes defined in RFC 8460 the additional URI scheme "directory:" as a directory in the filesystem where reports are to be saved as files to allow inspection and debugging.

Rules in the *--mail_destination_map* can also introduce "https:" and "directory:" URIs as report destinations.
Rules in the *--http_upload_map* can also introduce "https:" and "directory:" URIs as report destinations.
No further processing is done with those destinations, i.e. a "https:" URI introduced in the *--mail_destination_map* is not put through the transformations from *--http_upload_map* and vice versa.

The results from *--tlsrpt_record_map* which is processed first, however, are put through the transformations of *--http_upload_map* and *--mail_destination_map* even if *--tlsrpt_record_map* already had actions modify the report destinations.




== Examples

Retrieve data from a local fetcher with standard configuration and from another local fetcher with a different storage:

*tlsrpt-reportd --fetchers "tlsrpt-fetcher, tlsrpt-fetcher --storage sqlite:///tmp/test.sqlite"*

Retrieve data from a local fetcher and a remote fetcher:

*tlsrpt-reportd --fetchers "tlsrpt-fetcher, ssh user@remote tlsrpt-fetcher"*



== Exit status
*0*::
Success.

*1*::
Failure.


== See also
man:tlsrpt-collectd[1], man:tlsrpt-fetcher[1]

include::manpage-copying.adoc[]

